name: Tester
on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  execute_py:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Run script file
      run:  echo "Hollo my name is MYSQL"