name: Wanhua 119
on:
  push:
    branches:
      - main
#  schedule:
#    - cron: '*/5 * * * *'

jobs:
  execute_py:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - shell: Run script file
      env:
        SUPER_SECRET: ${{ secrets.SuperSecret }}
        SUPER_VAR: ${{ secrets.TESTVAR }}
      run: |
        python3 ./action_test.py