name: Wanhua 119
on:
  push:
    branches:
      - main
#  schedule:
#    - cron: '*/5 * * * *'

jobs:
  execute_py:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run script file
      env:
        LINE_TOKENS: ${{ secrets.LINE_TOKENS }}
      run: |
        pip install pytz
        chmod +x ./wanhua119.py
        ./wanhua119.py