name: Wanhua 119
on:
  push:
    branches:
      - main
  schedule:
  - cron: '*/5 * * * *'   # every 5 minutes

jobs:
  execute_py:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Run script file
      env:
        LINE_TOKENS: ${{ secrets.LINE_TOKENS }}
      run: |
        pip install pytz
        chmod +x ./wanhua119.py
        ./wanhua119.py